Footer
MehmetSunguralp/landify-project pull request #10
Opened 2022-08-01 07:22 UTC by MehmetSunguralp

![image](https://user-images.githubusercontent.com/78505988/182094743-5c2c0337-ba38-4f6f-af8d-962c6ee8e396.png)

2022-08-02 21:00 UTC, kumbu132 requested changes
Good job so far. I tested it out, and it looks good on my phone too. The coding, however, could be improved. Some of the comments I made apply to your other PRs as well, let's update them accordingly and then we can merge. Great work.

2022-08-02 21:00 UTC, kumbu132 commented on cta/cta.css
> +#cta-base {
- [ ] Lets try to avoid using ids in our CSS. lets stick with classes only

2022-08-02 21:00 UTC, kumbu132 commented on cta/cta.css
> +	height: 491px;
- [ ] Use rounded/even values for px

2022-08-02 21:00 UTC, kumbu132 commented on cta/cta.css
> +	margin: 0;
- [ ] define resets like `margin: 0` in a global css file. (i.e. 
```
* {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
      }
```

2022-08-02 21:00 UTC, kumbu132 commented on cta/cta.css
> +	margin: 32px 0 10px 0;
- [ ] - Simplify this to `margin: 32px 0 10px;`

2022-08-02 21:00 UTC, kumbu132 commented on cta/cta.css
> +	margin: 0 6px 0 0;
- [ ] Make this margin-right: 6px;

2022-08-02 21:00 UTC, kumbu132 commented on cta/cta.html
> +<!DOCTYPE html>
The indentation here could be better to make it more readable. Here's how to set up your Visual Stuido Code to make it better in terms of readability. 

1. Open VS Code
2. Search for `Prettier` in extensions and install it.. 
![image](https://user-images.githubusercontent.com/71005514/182471035-203eea3b-649f-412b-92cd-12d9065329e7.png)

3.  Open settings (you can use the keyboard shortcut `Ctrl + ,`)
4. Search for `formatter` and make sure prettier is enabled as the default formatter
![image](https://user-images.githubusercontent.com/71005514/182471507-486f92c7-70cd-4e72-969a-a0aec9129d7f.png)

5. Make sure that `Format on Paste` and `Format on Save` are checked. 
![image](https://user-images.githubusercontent.com/71005514/182471814-4caebb5c-c8fa-4890-a5da-002b279ccda1.png)

6. Save all your files again (i.e. open them and press `Ctrl + S`) and watch them get formatted properly.

2022-08-03 11:30 UTC, MehmetSunguralp commented on cta/cta.css
> +	height: 491px;
I think, I directly copied the value from the original design. I'll fix it, though.

2022-08-06 10:55 UTC, merged